import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Linking, Modal, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "@/src/services/api";
import { fechaCorta, horaCorta, obtenerRegional, REGIONAL_DEFAULT, Regional } from "@/src/services/regional";

type Cliente={id:number;nombre:string;apellidos?:string;telefono?:string;email?:string;deuda?:number};
type Servicio={id:number;nombre:string;activo?:boolean};
type Profesional={id:number;nombre:string;apellidos?:string;activo?:boolean;servicios?:{id:number}[]};
type Dia={fecha:string;profesionales:{profesionalId:number;horas:string[]}[]};

export default function ClientesScreen(){
 const [regional,setRegional]=useState<Regional>(REGIONAL_DEFAULT);
 const [clientes,setClientes]=useState<Cliente[]>([]),[servicios,setServicios]=useState<Servicio[]>([]),[profesionales,setProfesionales]=useState<Profesional[]>([]);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");
 const [modal,setModal]=useState(false),[clienteId,setClienteId]=useState<number>(),[servicioId,setServicioId]=useState<number>(),[profesionalId,setProfesionalId]=useState<number>(),[horas,setHoras]=useState("1"),[minutos,setMinutos]=useState("0"),[enviando,setEnviando]=useState(false);
 const cargar=useCallback(async(r=false)=>{r?setRefresh(true):setLoading(true);setError("");try{const [c,s,p]=await Promise.all([api.get("/Clientes"),api.get("/Servicios"),api.get("/Profesionales")]);setClientes(Array.isArray(c.data)?c.data:[]);setServicios((s.data??[]).filter((x:Servicio)=>x.activo!==false));setProfesionales((p.data??[]).filter((x:Profesional)=>x.activo!==false));}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible cargar los clientes.");}finally{setLoading(false);setRefresh(false)}},[]);
 useEffect(()=>{obtenerRegional().then(setRegional);cargar()},[cargar]);
 const lista=useMemo(()=>{const x=q.trim().toLowerCase();return !x?clientes:clientes.filter(c=>[c.nombre,c.apellidos,c.telefono,c.email].filter(Boolean).join(" ").toLowerCase().includes(x))},[clientes,q]);
 const pros=useMemo(()=>!servicioId?profesionales:profesionales.filter(p=>(p.servicios??[]).some(s=>s.id===servicioId)),[profesionales,servicioId]);
 const total=(Number(horas)||0)*60+(Number(minutos)||0);
 const enviar=async()=>{const cliente=clientes.find(x=>x.id===clienteId),servicio=servicios.find(x=>x.id===servicioId),prof=profesionales.find(x=>x.id===profesionalId);if(!cliente)return setError("Selecciona un cliente.");if(!cliente.telefono)return setError("El cliente no tiene teléfono registrado.");if(!servicio)return setError("Selecciona un servicio.");if(total<=0)return setError("Selecciona una duración mayor a cero.");try{setEnviando(true);setError("");const r=await api.post("/Disponibilidad/semana-siguiente",{servicioId,duracionMinutos:total,profesionalId:profesionalId??null});const msg=mensaje(r.data,cliente,servicio,prof,regional);const tel=String(cliente.telefono).replace(/\D/g,"").replace(/^00/,"");if(!tel)throw new Error("Teléfono inválido");setModal(false);await Linking.openURL(`https://wa.me/${tel}?text=${encodeURIComponent(msg)}`)}catch(e:any){setError(e?.response?.data?.mensaje??e?.response?.data?.title??"No fue posible consultar la disponibilidad.");}finally{setEnviando(false)}};
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/><Text style={s.muted}>Cargando clientes...</Text></SafeAreaView>;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>cargar(true)}/>}>
  <View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Volver</Text></Pressable><Pressable onPress={()=>router.push("/nuevo-cliente")} style={s.newBtn}><Text style={s.newText}>＋ Nuevo</Text></Pressable></View>
  <Text style={s.title}>Clientes</Text><Text style={s.sub}>{clientes.length} cliente(s) activo(s)</Text>
  <TextInput value={q} onChangeText={setQ} placeholder="Buscar por nombre, teléfono o email" style={s.input} autoCapitalize="none"/>
  {error?<Text style={s.error}>{error}</Text>:null}
  <View style={s.card}>{lista.length?lista.map((c,i)=><Pressable key={c.id} onPress={()=>router.push(`/cliente/${c.id}`)} style={[s.row,i===lista.length-1&&s.last]}><View style={s.avatar}><Text style={s.avatarText}>{(c.nombre?.[0]??"?").toUpperCase()}</Text></View><View style={s.body}><Text style={s.name}>{[c.nombre,c.apellidos].filter(Boolean).join(" ")}</Text><Text style={s.detail}>{c.telefono||c.email||"Sin datos de contacto"}</Text>{Number(c.deuda)>0?<Text style={s.debt}>Saldo pendiente: {money(c.deuda)}</Text>:null}</View><Text style={s.chevron}>›</Text></Pressable>):<Text style={s.empty}>No encontramos clientes.</Text>}</View>
 </ScrollView>
 <View style={s.availabilityBar}><Pressable style={s.waBtn} onPress={()=>{setError("");setClienteId(undefined);setServicioId(undefined);setProfesionalId(undefined);setHoras("1");setMinutos("0");setModal(true)}}><Text style={s.waText}>💬 Enviar disponibilidad</Text></Pressable></View>
 <Modal visible={modal} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setModal(false)}><SafeAreaView style={s.modalPage}><ScrollView contentContainerStyle={s.modalContent}><View style={s.modalHead}><Text style={s.modalTitle}>Enviar disponibilidad</Text><Pressable onPress={()=>setModal(false)}><Text style={s.close}>✕</Text></Pressable></View><Text style={s.muted}>Consulta los próximos 15 días y abre WhatsApp con los horarios disponibles.</Text>
 <Text style={s.label}>Cliente *</Text><View style={s.choices}>{clientes.slice().sort((a,b)=>a.nombre.localeCompare(b.nombre,"es")).map(x=><Choice key={x.id} selected={clienteId===x.id} text={`${x.nombre} ${x.apellidos??""}${x.telefono?` · ${x.telefono}`:" · sin teléfono"}`} onPress={()=>setClienteId(x.id)}/>)}</View>
 <Text style={s.label}>Servicio *</Text><View style={s.choices}>{servicios.map(x=><Choice key={x.id} selected={servicioId===x.id} text={x.nombre} onPress={()=>{setServicioId(x.id);setProfesionalId(undefined)}}/>)}</View>
 <Text style={s.label}>Profesional</Text><Choice selected={!profesionalId} text="Cualquier profesional disponible" onPress={()=>setProfesionalId(undefined)}/>{pros.map(x=><Choice key={x.id} selected={profesionalId===x.id} text={`${x.nombre} ${x.apellidos??""}`.trim()} onPress={()=>setProfesionalId(x.id)}/>)}
 <Text style={s.label}>Duración estimada *</Text><View style={s.durationRow}><TextInput style={[s.modalInput,{flex:1}]} value={horas} onChangeText={setHoras} keyboardType="number-pad"/><Text style={s.unit}>h</Text><TextInput style={[s.modalInput,{flex:1}]} value={minutos} onChangeText={setMinutos} keyboardType="number-pad"/><Text style={s.unit}>min</Text></View>
 {error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={enviando||!clienteId||!servicioId||total<=0} onPress={enviar} style={[s.send,enviando&&s.disabled]}>{enviando?<ActivityIndicator color="#fff"/>:<Text style={s.sendText}>💬 Abrir WhatsApp</Text>}</Pressable></ScrollView></SafeAreaView></Modal>
 </SafeAreaView>
}
function Choice({selected,text,onPress}:{selected:boolean;text:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,selected&&s.choiceOn]}><Text style={[s.choiceText,selected&&s.choiceTextOn]}>{selected?"✓ ":""}{text}</Text></Pressable>}
function mensaje(datos:any,c:Cliente,sv:Servicio,p:Profesional|undefined,r:Regional){const lineas=[`Hola ${c.nombre} 😊`,"",`Te compartimos la disponibilidad para los próximos 15 días para *${sv.nombre}*${p?` con *${p.nombre} ${p.apellidos??""}*`:""}:`,""];const dias=(datos?.dias??[]).map((d:Dia)=>{const hs=p?(d.profesionales??[]).find(x=>Number(x.profesionalId)===Number(p.id))?.horas??[]:Array.from(new Set((d.profesionales??[]).flatMap(x=>x.horas??[]))).sort();return{...d,hs}}).filter((d:any)=>d.hs.length);if(!dias.length)lineas.push("Por el momento no tenemos espacios disponibles en los próximos 15 días para este servicio.");else{for(const d of dias)lineas.push(`📅 *${fechaCorta(d.fecha,r)}*: ${compactar(d.hs,Number(datos?.duracionSlotMinutos)||15,r).join(", ")}`);lineas.push("","Si alguno de estos horarios te funciona, me indicas cuál y te ayudo a reservarlo 😊")}return lineas.join("\n")}
function compactar(hs:string[],slot:number,r:Regional){const xs=hs.map(x=>{const[h,m]=x.split(":").map(Number);return h*60+m}).filter(Number.isFinite).sort((a,b)=>a-b);if(!xs.length)return[];const out:string[]=[];let ini=xs[0],ant=xs[0];for(let i=1;i<xs.length;i++){if(xs[i]-ant===slot){ant=xs[i];continue}out.push(rango(ini,ant,r));ini=ant=xs[i]}out.push(rango(ini,ant,r));return out}
function rango(a:number,b:number,r:Regional){const fmt=(n:number)=>horaCorta(`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`,r);return a===b?fmt(a):`${fmt(a)}–${fmt(b)}`}
const money=(v?:number)=>new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(v??0));
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:40},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},muted:{color:"#64748b"},header:{marginTop:8,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:"#2563eb",fontWeight:"800"},newBtn:{backgroundColor:"#111827",borderRadius:12,paddingHorizontal:14,paddingVertical:10},newText:{color:"#fff",fontWeight:"900"},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:22},sub:{color:"#64748b",marginTop:4},availabilityBar:{paddingHorizontal:20,paddingTop:10,paddingBottom:10,backgroundColor:"#f4f6f8"},waBtn:{backgroundColor:"#16a34a",borderRadius:16,padding:15,alignItems:"center"},waText:{color:"#fff",fontWeight:"900"},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:16,paddingHorizontal:15,paddingVertical:13,marginTop:14,color:"#111827"},card:{backgroundColor:"#fff",borderRadius:20,paddingHorizontal:16,marginTop:14},row:{flexDirection:"row",alignItems:"center",paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},last:{borderBottomWidth:0},avatar:{width:42,height:42,borderRadius:21,backgroundColor:"#e2e8f0",alignItems:"center",justifyContent:"center",marginRight:12},avatarText:{fontWeight:"900",color:"#334155"},body:{flex:1},chevron:{color:"#94a3b8",fontSize:28,marginLeft:8},name:{fontWeight:"900",color:"#111827"},detail:{color:"#64748b",fontSize:12,marginTop:3},debt:{color:"#be123c",fontSize:11,fontWeight:"800",marginTop:4},empty:{paddingVertical:28,textAlign:"center",color:"#64748b"},error:{color:"#be123c",backgroundColor:"#fff1f2",padding:12,borderRadius:12,marginTop:12},modalPage:{flex:1,backgroundColor:"#f4f6f8"},modalContent:{padding:20,paddingBottom:40},modalHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:6},modalTitle:{fontSize:24,fontWeight:"900",color:"#111827"},close:{fontSize:22,color:"#64748b"},label:{fontWeight:"900",color:"#334155",marginTop:18,marginBottom:8},choices:{gap:7},choice:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:13,padding:12,marginBottom:7},choiceOn:{borderColor:"#2563eb",backgroundColor:"#eff6ff"},choiceText:{color:"#334155",fontWeight:"700"},choiceTextOn:{color:"#1d4ed8"},durationRow:{flexDirection:"row",alignItems:"center",gap:8},modalInput:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:13,padding:12},unit:{fontWeight:"800",color:"#64748b"},send:{backgroundColor:"#16a34a",borderRadius:16,padding:16,alignItems:"center",marginTop:20},sendText:{color:"#fff",fontWeight:"900"},disabled:{opacity:.5}});
