import { router } from "expo-router";import { useEffect,useState } from "react";import { ActivityIndicator,Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,TextInput,View } from "react-native";import api from "@/src/services/api";import {limpiarRegional} from "@/src/services/regional";
type C={logoUrl?:string;frasePresentacion?:string;colorPrimario?:string;colorSecundario?:string;colorFondo?:string;moneda?:string;zonaHoraria?:string;idioma?:string;duracionSlotMinutos?:number;permitirReservaOnline?:boolean;mostrarPrecios?:boolean;recordatorioEmailActivo?:boolean;recordatorioWhatsAppActivo?:boolean;recordatorioEmailHorasAntes?:number;requiereDeposito?:boolean;porcentajeDeposito?:number;instagram?:string;facebook?:string;whatsApp?:string};type D={nombre:string;nombreComercial?:string;identificacion?:string;telefono?:string;email?:string;slugPublico?:string;landingPublicaActiva?:boolean;configuracion?:C};
export default function Configuracion(){const[d,setD]=useState<D|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{api.get("/Configuracion").then(r=>setD(r.data)).catch((e:any)=>setError(e?.response?.data?.mensaje??"No fue posible cargar la configuración.")).finally(()=>setLoading(false))},[]);
 const set=(k:keyof D,v:any)=>setD(x=>x?{...x,[k]:v}:x),setc=(k:keyof C,v:any)=>setD(x=>x?{...x,configuracion:{...x.configuracion,[k]:v}}:x);
 const save=async()=>{if(!d)return;const x=d.configuracion??{};try{setSaving(true);setError("");await api.put("/Configuracion",{nombre:d.nombre,nombreComercial:d.nombreComercial||null,identificacion:d.identificacion||null,telefono:d.telefono||null,email:d.email||null,logoUrl:x.logoUrl||null,frasePresentacion:x.frasePresentacion||null,colorPrimario:x.colorPrimario||"#111827",colorSecundario:x.colorSecundario||"#2563EB",colorFondo:x.colorFondo||"#FFFFFF",moneda:x.moneda||"CRC",zonaHoraria:x.zonaHoraria||"America/Costa_Rica",idioma:x.idioma||"es",duracionSlotMinutos:Number(x.duracionSlotMinutos||30),permitirReservaOnline:!!x.permitirReservaOnline,mostrarPrecios:!!x.mostrarPrecios,recordatorioEmailActivo:!!x.recordatorioEmailActivo,recordatorioWhatsAppActivo:!!x.recordatorioWhatsAppActivo,recordatorioEmailHorasAntes:Number(x.recordatorioEmailHorasAntes||24),requiereDeposito:!!x.requiereDeposito,porcentajeDeposito:Number(x.porcentajeDeposito||0),instagram:x.instagram||null,facebook:x.facebook||null,whatsApp:x.whatsApp||null});limpiarRegional();Alert.alert("Listo","Configuración actualizada correctamente.")}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible guardar la configuración.")}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/></SafeAreaView>;if(!d)return <SafeAreaView style={s.page}><Text style={s.error}>{error}</Text></SafeAreaView>;const x=d.configuracion??{};
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Dashboard</Text></Pressable><Text style={s.title}>Configuración</Text><Text style={s.sub}>Negocio, reservas y recordatorios</Text>{error?<Text style={s.error}>{error}</Text>:null}
 <Section t="Negocio"/><Field l="Nombre" v={d.nombre} set={v=>set("nombre",v)}/><Field l="Nombre comercial" v={d.nombreComercial} set={v=>set("nombreComercial",v)}/><Field l="Teléfono" v={d.telefono} set={v=>set("telefono",v)} phone/><Field l="Email" v={d.email} set={v=>set("email",v)}/><Field l="Frase de presentación" v={x.frasePresentacion} set={v=>setc("frasePresentacion",v)}/>
 <Section t="Reservas"/><Toggle l="Permitir reserva online" v={!!x.permitirReservaOnline} set={v=>setc("permitirReservaOnline",v)}/><Toggle l="Mostrar precios" v={!!x.mostrarPrecios} set={v=>setc("mostrarPrecios",v)}/><Field l="Duración del slot (min)" v={String(x.duracionSlotMinutos??30)} set={v=>setc("duracionSlotMinutos",Number(v)||0)} num/>
 <Section t="Recordatorios"/><Toggle l="Email automático" v={!!x.recordatorioEmailActivo} set={v=>setc("recordatorioEmailActivo",v)}/><Toggle l="WhatsApp automático" v={!!x.recordatorioWhatsAppActivo} set={v=>setc("recordatorioWhatsAppActivo",v)}/><Field l="Horas antes" v={String(x.recordatorioEmailHorasAntes??24)} set={v=>setc("recordatorioEmailHorasAntes",Number(v)||0)} num/>
 <Section t="Depósito"/><Toggle l="Requiere depósito" v={!!x.requiereDeposito} set={v=>setc("requiereDeposito",v)}/>{x.requiereDeposito?<Field l="Porcentaje %" v={String(x.porcentajeDeposito??0)} set={v=>setc("porcentajeDeposito",Number(v)||0)} num/>:null}
 <Section t="Regional"/><Field l="Moneda" v={x.moneda} set={v=>setc("moneda",v)}/><Field l="Zona horaria" v={x.zonaHoraria} set={v=>setc("zonaHoraria",v)}/><Field l="Idioma" v={x.idioma} set={v=>setc("idioma",v)}/>
 <Section t="Redes"/><Field l="WhatsApp" v={x.whatsApp} set={v=>setc("whatsApp",v)} phone/><Field l="Instagram" v={x.instagram} set={v=>setc("instagram",v)}/><Field l="Facebook" v={x.facebook} set={v=>setc("facebook",v)}/>
 <Pressable disabled={saving} onPress={save} style={[s.save,saving&&s.disabled]}><Text style={s.saveText}>{saving?"Guardando...":"Guardar cambios"}</Text></Pressable><Text style={s.note}>Los cambios de recordatorios pueden reprogramar notificaciones futuras, igual que en la versión web.</Text>
 </ScrollView></SafeAreaView>}
function Section({t}:{t:string}){return <Text style={s.section}>{t}</Text>}function Field({l,v,set,phone,num}:{l:string;v?:string;set:(v:string)=>void;phone?:boolean;num?:boolean}){return <View style={s.field}><Text style={s.label}>{l}</Text><TextInput value={v??""} onChangeText={set} style={s.input} keyboardType={num?"number-pad":phone?"phone-pad":"default"} autoCapitalize="none"/></View>}function Toggle({l,v,set}:{l:string;v:boolean;set:(v:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleText}>{l}</Text><Switch value={v} onValueChange={set}/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:"center",justifyContent:"center"},back:{color:"#2563eb",fontWeight:"800",marginTop:8},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:20},sub:{color:"#64748b",marginTop:4},error:{backgroundColor:"#fff1f2",color:"#be123c",padding:12,borderRadius:12,marginTop:14},section:{fontSize:18,fontWeight:"900",color:"#111827",marginTop:24,marginBottom:10},field:{marginBottom:10},label:{color:"#475569",fontWeight:"700",fontSize:12,marginBottom:6},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:14,paddingHorizontal:14,paddingVertical:12,color:"#111827"},toggle:{backgroundColor:"#fff",borderRadius:14,paddingHorizontal:14,paddingVertical:10,marginBottom:9,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},toggleText:{fontWeight:"800",color:"#111827"},save:{backgroundColor:"#2563eb",borderRadius:16,padding:16,alignItems:"center",marginTop:26},saveText:{color:"#fff",fontWeight:"900",fontSize:16},disabled:{opacity:.5},note:{color:"#64748b",fontSize:11,lineHeight:17,textAlign:"center",marginTop:12}});
