import { router } from "expo-router";
import { useCallback,useEffect,useState } from "react";
import { ActivityIndicator,Linking,Pressable,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import api from "@/src/services/api";
import {obtenerUsuario,UsuarioSesion} from "@/src/services/session";

type Suscripcion={accessAllowed?:boolean;accessSource?:string;trialActive?:boolean;trialDaysRemaining?:number;trialEndsAt?:string;paypalActive?:boolean;paypalPaidThrough?:boolean;paypalAccessUntil?:string;manualActive?:boolean;courtesyActive?:boolean;metodoSuscripcion?:string;suscripcionHasta?:string;notaSuscripcion?:string;subscriptionId?:string;status?:string;nextBillingTime?:string};
type Config={price?:string;currency?:string;mode?:string};
const WEB="https://barberiasaas.com/mi-suscripcion";
const ADMIN="50660662375";

export default function MiSuscripcion(){const[s,setS]=useState<Suscripcion|null>(null),[config,setConfig]=useState<Config|null>(null),[u,setU]=useState<UsuarioSesion|null>(null),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(r=false)=>{r?setRefresh(true):setLoading(true);setError("");try{const[a,b,user]=await Promise.all([api.get("/paypal/subscription-current"),api.get("/paypal/subscription-config"),obtenerUsuario()]);setS(a.data??null);setConfig(b.data??null);setU(user)}catch(e:any){setError(e?.response?.data?.message??"No se pudo cargar la suscripción.")}finally{setLoading(false);setRefresh(false)}},[]);
 useEffect(()=>{load()},[load]);
 const paypal=String(s?.status||"").toUpperCase(),activa=Boolean(s?.accessAllowed),fuente=s?.courtesyActive?"Cortesía":s?.paypalActive?"PayPal":s?.paypalPaidThrough?"PayPal":s?.manualActive?(s?.metodoSuscripcion||"Pago manual"):s?.trialActive?"Prueba gratuita":"Sin acceso";
 const abrirPago=()=>Linking.openURL(WEB);
 const contactar=()=>{const msg=`Hola, me gustaría seguir usando Barbería SaaS. ¿Me puedes ayudar con mi suscripción?\n\nNegocio: ${u?.negocio||"mi negocio"}\nCorreo: ${u?.email||"—"}`;Linking.openURL(`https://wa.me/${ADMIN}?text=${encodeURIComponent(msg)}`)};
 if(loading)return <SafeAreaView style={st.center}><ActivityIndicator size="large"/><Text style={st.muted}>Consultando tu suscripción...</Text></SafeAreaView>;
 return <SafeAreaView style={st.page}><ScrollView contentContainerStyle={st.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>load(true)}/>}><Pressable onPress={()=>router.back()}><Text style={st.back}>‹ Dashboard</Text></Pressable><Text style={st.kicker}>BARBERÍA SAAS</Text><Text style={st.title}>Mi suscripción</Text><Text style={st.muted}>Administra el plan de tu negocio y mantén activo el acceso.</Text>{error?<View style={st.error}><Text style={st.errorText}>{error}</Text></View>:null}
 <View style={st.plan}><View style={st.row}><View><Text style={st.pill}>PLAN MENSUAL</Text><Text style={st.planTitle}>Barbería SaaS</Text></View><View><Text style={st.price}>${config?.currency==="USD"?"$":config?.currency||"USD"}{config?.price||"10.00"}</Text><Text style={st.currency}>{config?.currency||"USD"}/mes</Text></View></View><Text style={st.feature}>✓ Agenda, clientes y profesionales</Text><Text style={st.feature}>✓ Ventas, caja y cuentas por cobrar</Text><Text style={st.feature}>✓ Reportes y control del negocio</Text><Text style={st.feature}>✓ Renovación automática mensual con PayPal</Text></View>
 <View style={[st.statusBox,activa?st.active:st.inactive]}><Text style={st.statusTitle}>{activa?"✓ Acceso activo":"⚠ Acceso inactivo"}</Text><Text style={st.statusText}>Método: {fuente}</Text>{s?.trialActive?<Text style={st.statusText}>Prueba: {s.trialDaysRemaining??0} día(s) restante(s)</Text>:null}{paypal?<Text style={st.statusText}>Estado PayPal: {paypal}</Text>:null}{s?.nextBillingTime?<Text style={st.statusText}>Próxima renovación: {date(s.nextBillingTime)}</Text>:null}{s?.paypalPaidThrough&&s?.paypalAccessUntil?<Text style={st.statusText}>Acceso PayPal hasta: {date(s.paypalAccessUntil)}</Text>:null}{s?.manualActive&&s?.suscripcionHasta?<Text style={st.statusText}>Acceso hasta: {date(s.suscripcionHasta)}</Text>:null}{s?.notaSuscripcion?<Text style={st.note}>Nota: {s.notaSuscripcion}</Text>:null}</View>
 <Pressable style={st.pay} onPress={abrirPago}><Text style={st.payText}>PayPal · Administrar / pagar</Text></Pressable><Text style={st.help}>El pago se abre en la página segura de Barbería SaaS, que usa la integración de PayPal ya probada en Web. Al regresar, desliza hacia abajo para actualizar el estado.</Text><Pressable style={st.whatsapp} onPress={contactar}><Text style={st.whatsappText}>💬 Contactar al administrador</Text></Pressable>
 {config?.mode?.toLowerCase()==="sandbox"?<Text style={st.sandbox}>PayPal Sandbox · No se cobrará dinero real.</Text>:null}<View style={st.account}><Text style={st.accountTitle}>Tu cuenta</Text><Text style={st.label}>Negocio</Text><Text style={st.value}>{u?.negocio||"Tu negocio"}</Text><Text style={st.label}>Correo</Text><Text style={st.value}>{u?.email||"—"}</Text></View></ScrollView></SafeAreaView>}
function date(v:string){try{return new Date(v).toLocaleString()}catch{return v}}
const st=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:40},back:{color:"#2563eb",fontWeight:"800",marginTop:8},kicker:{color:"#2563eb",fontSize:12,fontWeight:"900",letterSpacing:1.2,marginTop:25},title:{fontSize:28,fontWeight:"900",color:"#111827",marginTop:4},muted:{color:"#64748b",marginTop:5},error:{backgroundColor:"#fff1f2",padding:14,borderRadius:14,marginTop:16},errorText:{color:"#be123c"},plan:{backgroundColor:"#fff",borderRadius:22,padding:20,marginTop:18},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},pill:{fontSize:10,fontWeight:"900",color:"#64748b"},planTitle:{fontSize:21,fontWeight:"900",color:"#111827",marginTop:5},price:{fontSize:27,fontWeight:"900",color:"#111827",textAlign:"right"},currency:{fontSize:11,color:"#64748b",textAlign:"right"},feature:{color:"#334155",marginTop:13},statusBox:{borderRadius:18,padding:17,marginTop:14},active:{backgroundColor:"#e8f7ee"},inactive:{backgroundColor:"#fff7ed"},statusTitle:{fontSize:17,fontWeight:"900",color:"#111827"},statusText:{color:"#475569",marginTop:6},note:{color:"#475569",fontStyle:"italic",marginTop:8},pay:{backgroundColor:"#0070ba",borderRadius:15,padding:15,alignItems:"center",marginTop:14},payText:{color:"#fff",fontWeight:"900"},help:{fontSize:11,color:"#64748b",lineHeight:16,textAlign:"center",marginTop:8},whatsapp:{backgroundColor:"#fff",borderRadius:15,padding:15,alignItems:"center",marginTop:10},whatsappText:{fontWeight:"900",color:"#111827"},sandbox:{color:"#64748b",fontSize:11,textAlign:"center",marginTop:10},account:{backgroundColor:"#fff",borderRadius:18,padding:18,marginTop:18},accountTitle:{fontSize:17,fontWeight:"900",color:"#111827",marginBottom:12},label:{fontSize:11,color:"#94a3b8",marginTop:8},value:{fontWeight:"800",color:"#111827",marginTop:2}});
