import { Contact } from "expo-contacts";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "@/src/services/api";
export default function NuevoClienteScreen(){
 const{id}=useLocalSearchParams<{id?:string}>();const edit=!!id;const[loading,setLoading]=useState(edit);
 const[paisCodigoTelefono,setPaisCodigoTelefono]=useState<string|null>(null),[fechaNacimiento,setFechaNacimiento]=useState<string|null>(null);\n const[nombre,setNombre]=useState(""),[apellidos,setApellidos]=useState(""),[telefono,setTelefono]=useState(""),[email,setEmail]=useState(""),[notas,setNotas]=useState(""),[saving,setSaving]=useState(false),[importing,setImporting]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!edit)return;api.get(`/Clientes/${id}`).then(r=>{const x=r.data??{};setNombre(x.nombre??"");setApellidos(x.apellidos??"");setTelefono(x.telefono??"");setPaisCodigoTelefono(x.paisCodigoTelefono??null);setFechaNacimiento(x.fechaNacimiento??null);setEmail(x.email??"");setNotas(x.notas??"")}).catch((e:any)=>setError(e?.response?.data?.mensaje??"No fue posible cargar el cliente.")).finally(()=>setLoading(false))},[edit,id]);
 const importar=async()=>{setImporting(true);setError("");try{const c=await Contact.presentPicker();if(!c)return;const[n,a,phones,emails]=await Promise.all([c.getGivenName(),c.getFamilyName(),c.getPhones(),c.getEmails()]);setNombre(n??"");setApellidos(a??"");setTelefono(phones[0]?.number??"");setEmail(emails[0]?.address??"");}catch{setError("No fue posible abrir o leer el contacto seleccionado.");}finally{setImporting(false)}};
 const guardar=async()=>{if(!nombre.trim()){setError("El nombre es requerido.");return;}setSaving(true);setError("");try{const payload={nombre:nombre.trim(),apellidos:apellidos.trim(),telefono:telefono.trim()||null,paisCodigoTelefono:edit?paisCodigoTelefono:null,email:email.trim()||null,fechaNacimiento:edit?fechaNacimiento:null,notas:notas.trim()||null};if(edit)await api.put(`/Clientes/${id}`,payload);else await api.post("/Clientes",payload);Alert.alert(edit?"Cliente actualizado":"Cliente creado",edit?"Los datos se actualizaron correctamente.":"El cliente quedó registrado correctamente.",[{text:"OK",onPress:()=>router.replace(edit?`/cliente/${id}`:"/clientes")}]);}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible crear el cliente.");}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={s.loading}><ActivityIndicator size="large"/></SafeAreaView>;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Volver</Text></Pressable><Text style={s.title}>{edit?"Editar cliente":"Nuevo cliente"}</Text><Text style={s.sub}>{edit?"Actualiza los datos del cliente.":"Agrégalo manualmente o impórtalo desde tus contactos."}</Text>
 {!edit?<Pressable disabled={importing} onPress={importar} style={s.importBtn}>{importing?<ActivityIndicator/>:<Text style={s.importText}>📱 Importar de contactos</Text>}</Pressable>:null}{!edit?<Text style={s.privacy}>Solo usamos el contacto que tú selecciones. Puedes revisar los datos antes de guardarlos.</Text>:null}
 <Field label="Nombre *" value={nombre} onChange={setNombre}/><Field label="Apellidos" value={apellidos} onChange={setApellidos}/><Field label="Teléfono" value={telefono} onChange={setTelefono} keyboard="phone-pad" placeholder="Número de teléfono"/><Field label="Email" value={email} onChange={setEmail} keyboard="email-address" autoCapitalize="none"/><Field label="Notas" value={notas} onChange={setNotas} multiline/>
 {error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}<Pressable disabled={saving} onPress={guardar} style={[s.save,saving&&s.disabled]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>{edit?"Guardar cambios":"Guardar cliente"}</Text>}</Pressable>
 </ScrollView></SafeAreaView>
}
function Field({label,value,onChange,keyboard="default",placeholder="",autoCapitalize="sentences",multiline=false}:any){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard} placeholder={placeholder} autoCapitalize={autoCapitalize} multiline={multiline} style={[s.input,multiline&&s.notes]}/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:40},back:{color:"#2563eb",fontWeight:"800",marginTop:8},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:22},sub:{color:"#64748b",lineHeight:20,marginTop:5},importBtn:{backgroundColor:"#ecfdf5",borderWidth:1,borderColor:"#86efac",borderRadius:16,padding:15,alignItems:"center",marginTop:22},importText:{color:"#166534",fontWeight:"900"},privacy:{color:"#64748b",fontSize:11,lineHeight:17,marginTop:8},field:{marginTop:16},label:{color:"#334155",fontWeight:"800",marginBottom:7},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:14,paddingHorizontal:14,paddingVertical:12,color:"#111827"},notes:{minHeight:90,textAlignVertical:"top"},errorBox:{backgroundColor:"#fff1f2",borderRadius:14,padding:13,marginTop:16},error:{color:"#be123c"},save:{backgroundColor:"#111827",borderRadius:16,padding:16,alignItems:"center",marginTop:20},saveText:{color:"#fff",fontWeight:"900"},disabled:{opacity:.6}});
