import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "@/src/services/api";import {dinero,fechaHora as fechaRegional,obtenerRegional,Regional} from "@/src/services/regional";
import { obtenerUsuario } from "@/src/services/session";
type Sucursal={id:number;nombre:string};type Cliente={id:number;nombre:string;apellidos?:string};type Producto={id:number;nombre:string;categoria?:string;codigo?:string;precioVenta?:number;stockTotal?:number;activo?:boolean};type Item={productoId:number;nombre:string;precio:number;stock:number;cantidad:number};
export default function NuevaVenta(){const[regional,setRegional]=useState<Regional>({moneda:"CRC",zonaHoraria:"America/Costa_Rica",idioma:"es",locale:"es-CR"});
 const[sucursales,setSucursales]=useState<Sucursal[]>([]),[clientes,setClientes]=useState<Cliente[]>([]),[productos,setProductos]=useState<Producto[]>([]),[metodos,setMetodos]=useState<string[]>([]);
 const[sucursalId,setSucursalId]=useState<number|undefined>(),[clienteId,setClienteId]=useState<number|undefined>(),[metodo,setMetodo]=useState("Efectivo"),[q,setQ]=useState(""),[cq,setCq]=useState(""),[carrito,setCarrito]=useState<Item[]>([]),[descuento,setDescuento]=useState(""),[notas,setNotas]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{obtenerRegional().then(setRegional);(async()=>{try{const u=await obtenerUsuario();const[a,b,c]=await Promise.all([api.get("/Sucursales"),api.get("/Clientes"),api.get("/Ventas/metodos-pago")]);const ss=a.data??[];setSucursales(ss);setClientes(b.data??[]);setMetodos(c.data??[]);setMetodo(c.data?.[0]??"Efectivo");setSucursalId(u?.sucursalId&&ss.some((x:Sucursal)=>x.id===u.sucursalId)?u.sucursalId:ss.length===1?ss[0].id:undefined)}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible preparar la venta.")}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!sucursalId){setProductos([]);setCarrito([]);return}(async()=>{try{setError("");const r=await api.get("/Productos",{params:{sucursalId}});setProductos((r.data??[]).filter((x:Producto)=>x.activo!==false));setCarrito([])}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible cargar los productos.")}})()},[sucursalId]);
 const lista=useMemo(()=>{const x=q.trim().toLowerCase();return productos.filter(p=>!x||[p.nombre,p.categoria,p.codigo].filter(Boolean).join(" ").toLowerCase().includes(x))},[productos,q]);
 const cl=useMemo(()=>{const x=cq.trim().toLowerCase();return clientes.filter(c=>!x||[c.nombre,c.apellidos].filter(Boolean).join(" ").toLowerCase().includes(x)).slice(0,12)},[clientes,cq]);
 const subtotal=carrito.reduce((a,x)=>a+x.precio*x.cantidad,0),desc=Math.max(0,Number(descuento)||0),total=Math.max(0,subtotal-desc);
 const add=(p:Producto)=>{const stock=Number(p.stockTotal??0);if(stock<=0)return;setCarrito(a=>{const e=a.find(x=>x.productoId===p.id);if(e){if(e.cantidad>=stock)return a;return a.map(x=>x.productoId===p.id?{...x,cantidad:x.cantidad+1}:x)}return[...a,{productoId:p.id,nombre:p.nombre,precio:Number(p.precioVenta??0),stock,cantidad:1}]})};
 const qty=(id:number,d:number)=>setCarrito(a=>a.map(x=>x.productoId===id?{...x,cantidad:Math.min(x.stock,x.cantidad+d)}:x).filter(x=>x.cantidad>0));
 const guardar=async()=>{if(!sucursalId)return setError("Selecciona una sucursal.");if(!carrito.length)return setError("Agrega al menos un producto.");if(desc>subtotal)return setError("El descuento no puede superar el subtotal.");try{setSaving(true);setError("");const r=await api.post("/Ventas",{sucursalId,clienteId:clienteId??null,metodoPago:metodo,descuento:desc,notas:notas.trim()||null,detalles:carrito.map(x=>({productoId:x.productoId,cantidad:x.cantidad}))});router.replace({pathname:"/cobrar-venta/[id]",params:{id:String(r.data.id)}})}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible registrar la venta.")}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/><Text>Cargando caja...</Text></SafeAreaView>;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Ventas</Text></Pressable><Text style={s.title}>Nueva venta</Text>
 {error?<Text style={s.error}>{error}</Text>:null}<Text style={s.label}>Sucursal</Text><View style={s.chips}>{sucursales.map(x=><Pressable key={x.id} onPress={()=>setSucursalId(x.id)} style={[s.chip,sucursalId===x.id&&s.chipOn]}><Text style={[s.chipText,sucursalId===x.id&&s.chipTextOn]}>{x.nombre}</Text></Pressable>)}</View>
 <Text style={s.label}>Productos</Text><TextInput style={s.input} value={q} onChangeText={setQ} placeholder="Buscar producto, código o categoría"/><View style={s.box}>{lista.map(p=><Pressable key={p.id} disabled={Number(p.stockTotal)<=0} onPress={()=>add(p)} style={s.product}><View style={{flex:1}}><Text style={s.bold}>{p.nombre}</Text><Text style={s.small}>{p.categoria||"Sin categoría"} · Stock {Number(p.stockTotal??0)}</Text></View><Text style={s.price}>{dinero(p.precioVenta,regional)}</Text><Text style={s.plus}>＋</Text></Pressable>)}</View>
 <Text style={s.label}>Venta actual</Text><View style={s.box}>{carrito.length?carrito.map(x=><View key={x.productoId} style={s.cart}><View style={{flex:1}}><Text style={s.bold}>{x.nombre}</Text><Text style={s.small}>{dinero(x.precio,regional)} c/u · {dinero(x.precio*x.cantidad,regional)}</Text></View><Pressable onPress={()=>qty(x.productoId,-1)} style={s.qty}><Text>−</Text></Pressable><Text style={s.count}>{x.cantidad}</Text><Pressable onPress={()=>qty(x.productoId,1)} style={s.qty}><Text>＋</Text></Pressable></View>):<Text style={s.empty}>Agrega productos arriba.</Text>}</View>
 <Text style={s.label}>Cliente opcional</Text><TextInput style={s.input} value={cq} onChangeText={setCq} placeholder="Buscar cliente"/><View style={s.chips}><Pressable onPress={()=>setClienteId(undefined)} style={[s.chip,!clienteId&&s.chipOn]}><Text style={[s.chipText,!clienteId&&s.chipTextOn]}>Sin cliente</Text></Pressable>{cl.map(x=><Pressable key={x.id} onPress={()=>setClienteId(x.id)} style={[s.chip,clienteId===x.id&&s.chipOn]}><Text style={[s.chipText,clienteId===x.id&&s.chipTextOn]}>{x.nombre} {x.apellidos}</Text></Pressable>)}</View>
 <Text style={s.label}>Método de pago</Text><View style={s.chips}>{metodos.map(x=><Pressable key={x} onPress={()=>setMetodo(x)} style={[s.chip,metodo===x&&s.chipOn]}><Text style={[s.chipText,metodo===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</View>
 <Text style={s.label}>Descuento</Text><TextInput style={s.input} value={descuento} onChangeText={setDescuento} keyboardType="decimal-pad" placeholder="0"/>
 <Text style={s.label}>Notas</Text><TextInput style={[s.input,s.notes]} value={notas} onChangeText={setNotas} multiline placeholder="Notas opcionales"/>
 <View style={s.total}><Row a="Subtotal" b={dinero(subtotal,regional)}/><Row a="Descuento" b={`- ${dinero(desc,regional)}`}/><View style={s.sep}/><Row a="Total" b={dinero(total,regional)} big/></View>
 <Pressable disabled={saving||!carrito.length} onPress={guardar} style={[s.pay,(saving||!carrito.length)&&s.disabled]}><Text style={s.payText}>{saving?"Procesando...":"💳 Registrar venta"}</Text></Pressable>
 </ScrollView></SafeAreaView>
}
function Row({a,b,big=false}:{a:string;b:string;big?:boolean}){return <View style={s.row}><Text style={big?s.big:s.small}>{a}</Text><Text style={big?s.big:s.bold}>{b}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:50},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},back:{color:"#2563eb",fontWeight:"800",marginTop:8},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:20},error:{backgroundColor:"#fff1f2",color:"#be123c",padding:12,borderRadius:12,marginTop:14},label:{fontWeight:"900",color:"#111827",marginTop:20,marginBottom:9},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:14,paddingHorizontal:14,paddingVertical:12},notes:{minHeight:75,textAlignVertical:"top"},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:999,paddingHorizontal:12,paddingVertical:9},chipOn:{backgroundColor:"#111827",borderColor:"#111827"},chipText:{color:"#334155",fontWeight:"700",fontSize:12},chipTextOn:{color:"#fff"},box:{backgroundColor:"#fff",borderRadius:18,paddingHorizontal:14},product:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:13,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},bold:{fontWeight:"900",color:"#111827"},small:{color:"#64748b",fontSize:12},price:{fontWeight:"900",color:"#111827"},plus:{fontSize:22,color:"#2563eb"},cart:{flexDirection:"row",alignItems:"center",paddingVertical:13,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},qty:{width:34,height:34,borderRadius:10,backgroundColor:"#f1f5f9",alignItems:"center",justifyContent:"center"},count:{width:30,textAlign:"center",fontWeight:"900"},empty:{paddingVertical:22,textAlign:"center",color:"#64748b"},total:{backgroundColor:"#111827",borderRadius:18,padding:18,marginTop:20,gap:9},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sep:{height:StyleSheet.hairlineWidth,backgroundColor:"#475569"},big:{color:"#fff",fontSize:22,fontWeight:"900"},pay:{backgroundColor:"#2563eb",borderRadius:16,padding:16,alignItems:"center",marginTop:14},payText:{color:"#fff",fontWeight:"900",fontSize:16},disabled:{opacity:.5}});
