import {router} from "expo-router";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ActivityIndicator,Pressable,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,View} from "react-native";
import api from "@/src/services/api";
import {dinero,fechaCorta,hoyRegional,obtenerRegional,REGIONAL_DEFAULT,Regional} from "@/src/services/regional";
type Tipo="dia"|"semana"|"mes";type Sucursal={id:number;nombre:string;activa?:boolean};type Dia={fecha:string;ingresosTotales?:number;servicios?:{ingresos?:number;cantidadCitas?:number};productos?:{ingresos?:number;cantidadVentas?:number;costo?:number;utilidadBruta?:number;descuentos?:number};ventasPorMetodoPago?:{metodoPago?:string;cantidadVentas?:number;total?:number}[]};
export default function Reportes(){const[regional,setRegional]=useState<Regional>(REGIONAL_DEFAULT),[tipo,setTipo]=useState<Tipo>("mes"),[fecha,setFecha]=useState(""),[sucursales,setSucursales]=useState<Sucursal[]>([]),[sucursal,setSucursal]=useState<number|null>(null),[dias,setDias]=useState<Dia[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");
 useEffect(()=>{obtenerRegional().then(r=>{setRegional(r);setFecha(x=>x||hoyRegional(r))});api.get("/Sucursales").then(x=>setSucursales(Array.isArray(x.data)?x.data:[])).catch(()=>{})},[]);
 const periodo=useMemo(()=>getPeriodo(tipo,fecha),[tipo,fecha]);
 const load=useCallback(async(r=false)=>{if(!fecha)return;r?setRefresh(true):setLoading(true);setError("");try{const rs=await Promise.all(fechas(periodo).map(f=>api.get("/ResumenFinanciero/diario",{params:{fecha:f,...(sucursal?{sucursalId:sucursal}:{})}})));setDias(rs.map(x=>x.data))}catch(e:any){setDias([]);setError(e?.response?.data?.mensaje??e?.response?.data?.title??"No fue posible cargar el reporte.")}finally{setLoading(false);setRefresh(false)}},[fecha,periodo.desde,periodo.hasta,sucursal]);
 useEffect(()=>{load()},[load]);
 const r=useMemo(()=>dias.reduce((a,d)=>{a.total+=Number(d.ingresosTotales||0);a.serv+=Number(d.servicios?.ingresos||0);a.citas+=Number(d.servicios?.cantidadCitas||0);a.prod+=Number(d.productos?.ingresos||0);a.ventas+=Number(d.productos?.cantidadVentas||0);a.costo+=Number(d.productos?.costo||0);a.util+=Number(d.productos?.utilidadBruta||0);a.desc+=Number(d.productos?.descuentos||0);for(const m of d.ventasPorMetodoPago||[]){const k=m.metodoPago||"Sin especificar",v=a.metodos[k]??{n:0,total:0};v.n+=Number(m.cantidadVentas||0);v.total+=Number(m.total||0);a.metodos[k]=v}return a},{total:0,serv:0,citas:0,prod:0,ventas:0,costo:0,util:0,desc:0,metodos:{} as Record<string,{n:number;total:number}>}),[dias]);
 const mover=(n:number)=>setFecha(moveRef(fecha,tipo,n));
 return <SafeAreaView style={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Dashboard</Text></Pressable><Text style={s.title}>Reportes</Text><View style={{width:80}}/></View><View style={s.tabs}>{(["dia","semana","mes"] as Tipo[]).map(x=><Pressable key={x} style={[s.tab,tipo===x&&s.tabOn]} onPress={()=>setTipo(x)}><Text style={[s.tabText,tipo===x&&s.tabTextOn]}>{x==="dia"?"Día":x==="semana"?"Semana":"Mes"}</Text></Pressable>)}</View><View style={s.nav}><Pressable onPress={()=>mover(-1)}><Text style={s.arrow}>‹</Text></Pressable><Pressable onPress={()=>setFecha(hoyRegional(regional))}><Text style={s.range}>{periodo.desde===periodo.hasta?fechaCorta(periodo.desde,regional):`${fechaCorta(periodo.desde,regional)} – ${fechaCorta(periodo.hasta,regional)}`}</Text><Text style={s.today}>Tocar para volver a hoy</Text></Pressable><Pressable onPress={()=>mover(1)}><Text style={s.arrow}>›</Text></Pressable></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.branchRow}><Pressable style={[s.branch,sucursal===null&&s.branchOn]} onPress={()=>setSucursal(null)}><Text style={[s.branchText,sucursal===null&&s.branchTextOn]}>Todas</Text></Pressable>{sucursales.filter(x=>x.activa!==false).map(x=><Pressable key={x.id} style={[s.branch,sucursal===x.id&&s.branchOn]} onPress={()=>setSucursal(x.id)}><Text style={[s.branchText,sucursal===x.id&&s.branchTextOn]}>{x.nombre}</Text></Pressable>)}</ScrollView>
 {loading?<View style={s.center}><ActivityIndicator size="large"/></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>load(true)}/>} >{error?<Text style={s.error}>{error}</Text>:null}<View style={s.hero}><Text style={s.heroLabel}>Ingresos totales</Text><Text style={s.heroValue}>{dinero(r.total,regional)}</Text><Text style={s.heroSub}>Dinero realmente recibido en el período</Text></View><View style={s.grid}><Card label="Servicios" value={dinero(r.serv,regional)} detail={`${r.citas} cita(s) completada(s)`}/><Card label="Productos" value={dinero(r.prod,regional)} detail={`${r.ventas} venta(s)`}/><Card label="Utilidad bruta" value={dinero(r.util,regional)} detail={`Costo: ${dinero(r.costo,regional)}`}/><Card label="Descuentos" value={dinero(r.desc,regional)} detail="Productos"/></View><Text style={s.section}>Métodos de pago</Text><View style={s.box}>{Object.entries(r.metodos).sort((a,b)=>b[1].total-a[1].total).map(([k,v])=><View key={k} style={s.line}><View><Text style={s.bold}>{k}</Text><Text style={s.small}>{v.n} cobro(s)</Text></View><Text style={s.bold}>{dinero(v.total,regional)}</Text></View>)}{!Object.keys(r.metodos).length?<Text style={s.empty}>No hay cobros en este período.</Text>:null}</View><Text style={s.section}>Detalle por día</Text><View style={s.box}>{dias.map(d=><View key={d.fecha} style={s.day}><Text style={s.dayDate}>{fechaCorta(d.fecha,regional)}</Text><View style={s.dayNums}><Text style={s.bold}>{dinero(d.ingresosTotales,regional)}</Text><Text style={s.small}>Servicios {dinero(d.servicios?.ingresos,regional)} · Productos {dinero(d.productos?.ingresos,regional)}</Text></View></View>)}{!dias.length?<Text style={s.empty}>No hay información para este período.</Text>:null}</View></ScrollView>}</SafeAreaView>}
function Card({label,value,detail}:{label:string;value:string;detail:string}){return <View style={s.card}><Text style={s.cardLabel}>{label}</Text><Text style={s.cardValue}>{value}</Text><Text style={s.small}>{detail}</Text></View>}
function parse(f:string){const[y,m,d]=f.split("-").map(Number);return new Date(y,m-1,d,12)}
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function getPeriodo(t:Tipo,f:string){if(!f)return{desde:"",hasta:""};const d=parse(f);if(t==="dia")return{desde:f,hasta:f};if(t==="semana"){const x=new Date(d),dow=x.getDay();x.setDate(x.getDate()+(dow===0?-6:1-dow));const y=new Date(x);y.setDate(x.getDate()+6);return{desde:iso(x),hasta:iso(y)}}return{desde:iso(new Date(d.getFullYear(),d.getMonth(),1,12)),hasta:iso(new Date(d.getFullYear(),d.getMonth()+1,0,12))}}
function fechas(p:{desde:string;hasta:string}){if(!p.desde)return[];const a=parse(p.desde),b=parse(p.hasta),r:string[]=[];while(a<=b){r.push(iso(a));a.setDate(a.getDate()+1)}return r}
function moveRef(f:string,t:Tipo,n:number){const d=parse(f);if(t==="dia")d.setDate(d.getDate()+n);else if(t==="semana")d.setDate(d.getDate()+7*n);else d.setMonth(d.getMonth()+n);return iso(d)}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},top:{padding:20,paddingBottom:8,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{width:80,color:"#2563eb",fontWeight:"800"},title:{fontSize:20,fontWeight:"900",color:"#111827"},tabs:{marginHorizontal:20,backgroundColor:"#e2e8f0",padding:3,borderRadius:14,flexDirection:"row"},tab:{flex:1,padding:9,alignItems:"center",borderRadius:11},tabOn:{backgroundColor:"#fff"},tabText:{fontWeight:"800",color:"#64748b"},tabTextOn:{color:"#111827"},nav:{margin:20,marginBottom:8,backgroundColor:"#fff",borderRadius:18,padding:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},arrow:{fontSize:30,color:"#2563eb",paddingHorizontal:8},range:{fontWeight:"900",color:"#111827",textAlign:"center",textTransform:"capitalize"},today:{fontSize:10,color:"#94a3b8",textAlign:"center",marginTop:2},branchRow:{paddingHorizontal:20,paddingBottom:10,gap:8},branch:{backgroundColor:"#fff",borderRadius:999,paddingHorizontal:14,paddingVertical:8},branchOn:{backgroundColor:"#111827"},branchText:{fontWeight:"800",color:"#64748b"},branchTextOn:{color:"#fff"},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{padding:20,paddingTop:8,paddingBottom:40},error:{color:"#be123c",backgroundColor:"#fff1f2",padding:14,borderRadius:14,marginBottom:12},hero:{backgroundColor:"#111827",borderRadius:22,padding:20},heroLabel:{color:"#cbd5e1"},heroValue:{color:"#fff",fontSize:32,fontWeight:"900",marginTop:7},heroSub:{color:"#94a3b8",fontSize:11,marginTop:4},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:10},card:{width:"48%",flexGrow:1,backgroundColor:"#fff",borderRadius:17,padding:15,minHeight:110},cardLabel:{color:"#64748b",fontSize:12,fontWeight:"700"},cardValue:{fontSize:18,fontWeight:"900",color:"#111827",marginTop:7},small:{fontSize:11,color:"#64748b",marginTop:4},section:{fontSize:18,fontWeight:"900",color:"#111827",marginTop:22,marginBottom:10},box:{backgroundColor:"#fff",borderRadius:18,paddingHorizontal:15},line:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:14,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},bold:{fontWeight:"900",color:"#111827"},empty:{color:"#64748b",textAlign:"center",paddingVertical:22},day:{flexDirection:"row",alignItems:"center",paddingVertical:14,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},dayDate:{width:100,fontWeight:"800",color:"#111827",textTransform:"capitalize"},dayNums:{flex:1,alignItems:"flex-end"}});
