import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "@/src/services/api";
type Venta={id:number;cliente?:string;metodoPago?:string;total?:number;estado?:string;fecha?:string;cantidadProductos?:number};
export default function VentasMobile(){
 const[ventas,setVentas]=useState<Venta[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");
 const cargar=useCallback(async(r=false)=>{r?setRefresh(true):setLoading(true);setError("");try{const x=await api.get("/Ventas",{params:{limite:100}});setVentas(Array.isArray(x.data)?x.data:[])}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible cargar las ventas.")}finally{setLoading(false);setRefresh(false)}},[]);
 useEffect(()=>{cargar()},[cargar]);
 const lista=useMemo(()=>{const x=q.trim().toLowerCase();return !x?ventas:ventas.filter(v=>[`#${v.id}`,v.cliente,v.metodoPago,v.estado].filter(Boolean).join(" ").toLowerCase().includes(x))},[ventas,q]);
 const total=ventas.filter(v=>v.estado==="Completada").reduce((a,v)=>a+Number(v.total??0),0);
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/><Text style={s.muted}>Cargando caja...</Text></SafeAreaView>;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>cargar(true)}/>}>
  <View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Volver</Text></Pressable><Pressable onPress={()=>router.push("/nueva-venta")} style={s.newBtn}><Text style={s.newText}>＋ Nueva venta</Text></Pressable></View>
  <Text style={s.title}>Ventas / Caja</Text><Text style={s.sub}>Productos, cobros e historial reciente</Text>
  <View style={s.hero}><Text style={s.heroLabel}>Total de ventas cargadas</Text><Text style={s.heroValue}>{money(total)}</Text><Text style={s.heroDetail}>{ventas.length} venta(s) reciente(s)</Text></View>
  <TextInput value={q} onChangeText={setQ} placeholder="Buscar venta, cliente o método de pago" style={s.input}/>
  {error?<Text style={s.error}>{error}</Text>:null}
  <View style={s.card}>{lista.length?lista.map((v,i)=><Pressable key={v.id} onPress={()=>router.push(`/venta/${v.id}`)} style={[s.row,i===lista.length-1&&s.last]}><View style={s.body}><View style={s.rowTop}><Text style={s.name}>Venta #{v.id}</Text><Text style={s.amount}>{money(v.total)}</Text></View><Text style={s.detail}>{v.cliente||"Sin cliente"} · {v.metodoPago||"Sin método"}</Text><Text style={s.detail}>{date(v.fecha)} · {v.estado||"Completada"} · {v.cantidadProductos??0} producto(s)</Text></View><Text style={s.chevron}>›</Text></Pressable>):<Text style={s.empty}>Aún no hay ventas.</Text>}</View>
 </ScrollView></SafeAreaView>
}
const money=(v?:number)=>new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(v??0));
const date=(v?:string)=>{if(!v)return"Sin fecha";const z=/Z$|[+-]\d{2}:\d{2}$/.test(v)?v:`${v}Z`;return new Intl.DateTimeFormat("es-CR",{timeZone:"America/Costa_Rica",day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(z))};
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:40},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},muted:{color:"#64748b"},header:{marginTop:8,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:"#2563eb",fontWeight:"800"},newBtn:{backgroundColor:"#111827",borderRadius:12,paddingHorizontal:14,paddingVertical:10},newText:{color:"#fff",fontWeight:"900"},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:22},sub:{color:"#64748b",marginTop:4},hero:{backgroundColor:"#111827",borderRadius:22,padding:20,marginTop:18},heroLabel:{color:"#cbd5e1",fontSize:12},heroValue:{color:"#fff",fontSize:30,fontWeight:"900",marginTop:6},heroDetail:{color:"#94a3b8",marginTop:4},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:16,paddingHorizontal:15,paddingVertical:13,marginTop:16},card:{backgroundColor:"#fff",borderRadius:20,paddingHorizontal:16,marginTop:14},row:{flexDirection:"row",alignItems:"center",paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},last:{borderBottomWidth:0},body:{flex:1},rowTop:{flexDirection:"row",justifyContent:"space-between",gap:10},name:{fontWeight:"900",color:"#111827"},amount:{fontWeight:"900",color:"#111827"},detail:{color:"#64748b",fontSize:12,marginTop:4},chevron:{color:"#94a3b8",fontSize:28,marginLeft:8},empty:{paddingVertical:28,textAlign:"center",color:"#64748b"},error:{color:"#be123c",marginTop:12}});
