import { router,useLocalSearchParams } from "expo-router";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import api from "@/src/services/api";
import {fechaHora,obtenerRegional,REGIONAL_DEFAULT,Regional} from "@/src/services/regional";

type Cita={id:number;fechaInicio?:string;fechaFin?:string;estado?:string;precio?:number;cliente?:{nombre?:string;apellidos?:string};servicio?:{nombre?:string};servicioVariante?:{nombre?:string}|null};
type Tipo="proximas"|"historial";

export default function CitasProfesional(){const{id,tipo,nombre}=useLocalSearchParams<{id:string;tipo?:string;nombre?:string}>();const[regional,setRegional]=useState<Regional>(REGIONAL_DEFAULT),[citas,setCitas]=useState<Cita[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");const modo:Tipo=tipo==="historial"?"historial":"proximas";
 const load=useCallback(async(r=false)=>{r?setRefresh(true):setLoading(true);setError("");try{const ahora=new Date(),desde=modo==="proximas"?ahora:new Date(ahora.getFullYear()-2,0,1),hasta=modo==="proximas"?new Date(ahora.getFullYear()+2,11,31,23,59,59):ahora;const x=await api.get("/Citas",{params:{desde:localParam(desde),hasta:localParam(hasta)}});setCitas(Array.isArray(x.data)?x.data:[])}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible cargar las citas.")}finally{setLoading(false);setRefresh(false)}},[modo]);
 useEffect(()=>{obtenerRegional().then(setRegional);load()},[load]);
 const filtradas=useMemo(()=>citas.filter((c:any)=>Number(c.profesional?.id)===Number(id)).filter(c=>modo==="proximas"?!["Completada","Cancelada","NoAsistio"].includes(c.estado??""):true).sort((a,b)=>modo==="proximas"?ts(a)-ts(b):ts(b)-ts(a)),[citas,id,modo]);
 return <SafeAreaView style={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Profesional</Text></Pressable><Text style={s.title}>{modo==="proximas"?"Próximas citas":"Historial de citas"}</Text><View style={{width:72}}/></View>{loading?<View style={s.center}><ActivityIndicator size="large"/></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>load(true)}/>}><Text style={s.person}>{nombre||"Profesional"}</Text><Text style={s.count}>{filtradas.length} {filtradas.length===1?"cita":"citas"}</Text>{error?<Text style={s.error}>{error}</Text>:null}{!error&&filtradas.length===0?<View style={s.empty}><Text style={s.icon}>📅</Text><Text style={s.emptyTitle}>{modo==="proximas"?"Sin próximas citas":"Sin historial"}</Text><Text style={s.muted}>{modo==="proximas"?"No hay citas futuras pendientes para este profesional.":"No hay citas anteriores en el período consultado."}</Text></View>:filtradas.map(c=><Pressable key={c.id} style={s.card} onPress={()=>router.push({pathname:"/cita/[id]",params:{id:String(c.id)}})}><View style={s.row}><Text style={s.date}>{fechaHora(c.fechaInicio,regional,{dateStyle:"medium",timeStyle:"short"})}</Text><Text style={[s.badge,badge(c.estado)]}>{estado(c.estado)}</Text></View><Text style={s.client}>{full(c.cliente)||"Cliente"}</Text><Text style={s.service}>{c.servicio?.nombre??"Servicio"}{c.servicioVariante?.nombre?` · ${c.servicioVariante.nombre}`:""}</Text></Pressable>)}</ScrollView>}</SafeAreaView>}
function localParam(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:00`}
function ts(c:Cita){if(!c.fechaInicio)return 0;const v=/Z$|[+-]\d{2}:\d{2}$/.test(c.fechaInicio)?c.fechaInicio:`${c.fechaInicio}Z`;return new Date(v).getTime()}
function full(x?:{nombre?:string;apellidos?:string}){return[x?.nombre,x?.apellidos].filter(Boolean).join(" ")}
function estado(v?:string){return v==="EnProceso"?"En proceso":v==="NoAsistio"?"No asistió":v??"Pendiente"}
function badge(v?:string){if(v==="Completada")return{backgroundColor:"#e8f7ee",color:"#16803d"};if(v==="Cancelada"||v==="NoAsistio")return{backgroundColor:"#fff1f2",color:"#be123c"};if(v==="Confirmada")return{backgroundColor:"#eaf2ff",color:"#2563eb"};return{backgroundColor:"#f1f5f9",color:"#475569"}}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},top:{padding:20,paddingBottom:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:"#2563eb",fontWeight:"800",width:72},title:{fontSize:18,fontWeight:"900",color:"#111827"},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{padding:20,paddingTop:8,paddingBottom:40},person:{fontSize:22,fontWeight:"900",color:"#111827"},count:{color:"#64748b",marginTop:3,marginBottom:16},error:{color:"#be123c",backgroundColor:"#fff1f2",padding:14,borderRadius:14,marginBottom:12},card:{backgroundColor:"#fff",borderRadius:18,padding:15,marginBottom:11},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:8},date:{fontWeight:"900",color:"#111827",flex:1},badge:{fontSize:10,fontWeight:"800",paddingHorizontal:8,paddingVertical:5,borderRadius:999,overflow:"hidden"},client:{fontSize:16,fontWeight:"900",color:"#111827",marginTop:10},service:{color:"#64748b",marginTop:4},empty:{backgroundColor:"#fff",borderRadius:18,padding:30,alignItems:"center"},icon:{fontSize:34},emptyTitle:{fontSize:18,fontWeight:"900",color:"#111827",marginTop:8},muted:{color:"#64748b",textAlign:"center",marginTop:5}});
