import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import api from "@/src/services/api";
type Cita={id:number;fechaInicio?:string;fechaFin?:string;precio?:number;estado?:string;notas?:string;cliente?:{nombre?:string;apellidos?:string;telefono?:string;email?:string};profesional?:{nombre?:string;apellidos?:string};servicio?:{nombre?:string};servicioVariante?:{nombre?:string}|null;sucursal?:{nombre?:string}};
export default function CitaDetalle(){
 const {id}=useLocalSearchParams<{id:string}>();const[cita,setCita]=useState<Cita|null>(null);const[error,setError]=useState("");const[actualizando,setActualizando]=useState(false);
 const cargar=useCallback(()=>{setError("");api.get(`/Citas/${id}`).then(r=>setCita(r.data)).catch(e=>setError(e?.response?.data?.mensaje??"No fue posible cargar la cita."));},[id]);
 useEffect(()=>{cargar();},[cargar]);
 const cambiarEstado=async(nuevo:string)=>{setActualizando(true);setError("");try{const r=await api.put(`/Citas/${id}/estado`,{estado:nuevo});setCita(v=>v?{...v,estado:r.data?.estado??nuevo}:v);if(nuevo==="Completada"){router.push({pathname:"/cobrar-cita/[id]",params:{id:String(id)}});return;}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible actualizar el estado.");}finally{setActualizando(false);}};
 const abrirWhatsApp=async(tipo:"confirmacion"|"recordatorio")=>{if(!cita)return;const telefono=String(cita.cliente?.telefono??"").replace(/\D/g,"").replace(/^00/,"");if(!telefono){setError("Este cliente no tiene un número de teléfono registrado para WhatsApp.");return;}const negocio="nuestro negocio";const cliente=cita.cliente?.nombre||nombre(cita.cliente)||"cliente";const servicio=cita.servicio?.nombre??"Servicio";const cuando=fechaHora(cita.fechaInicio);const intro=tipo==="confirmacion"?`Tu cita en *${negocio}* ha sido confirmada.`:`Te recordamos tu cita en *${negocio}*.`;const mensaje=[`Hola ${cliente} 😊`,"",intro,"",`📅 ${cuando}`,`✨ Servicio: ${servicio}`,"","Cualquier cambio me avisas. ¡Te esperamos! 💕"].join("\n");const url=`https://wa.me/${telefono}?text=${encodeURIComponent(mensaje)}`;try{await Linking.openURL(url);}catch{setError("No fue posible abrir WhatsApp en este dispositivo.");}};
 const confirmarCambio=(nuevo:string,etiqueta:string,peligroso=false)=>{if(peligroso){Alert.alert(etiqueta,`¿Seguro que deseas marcar esta cita como ${etiqueta.toLowerCase()}?`,[{text:"Volver",style:"cancel"},{text:etiqueta,style:"destructive",onPress:()=>cambiarEstado(nuevo)}]);return;}cambiarEstado(nuevo);};
 if(!cita&&!error)return <SafeAreaView style={s.loading}><ActivityIndicator size="large"/><Text style={s.muted}>Cargando cita...</Text></SafeAreaView>;
 return <SafeAreaView style={s.page}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Agenda</Text></Pressable><Text style={s.title}>Detalle de cita</Text><View style={{width:60}}/></View>
 <ScrollView contentContainerStyle={s.content}>{error?<View style={s.card}><Text style={s.error}>{error}</Text></View>:cita&&<>
   <View style={s.hero}><Text style={s.heroTime}>{fechaHora(cita.fechaInicio)}</Text><Text style={s.heroService}>{cita.servicio?.nombre??"Servicio"}</Text><Text style={s.heroStatus}>{estado(cita.estado)}</Text></View>
   <Section title="Cliente"><Row label="Nombre" value={nombre(cita.cliente)||"Cliente"}/><Row label="Teléfono" value={cita.cliente?.telefono||"—"}/><Row label="Email" value={cita.cliente?.email||"—"}/></Section>
   <Section title="Servicio"><Row label="Servicio" value={cita.servicio?.nombre||"—"}/>{cita.servicioVariante?.nombre?<Row label="Variante" value={cita.servicioVariante.nombre}/>:null}<Row label="Profesional" value={nombre(cita.profesional)||"—"}/><Row label="Sucursal" value={cita.sucursal?.nombre||"—"}/><Row label="Precio" value={moneda(cita.precio)}/></Section>
   {cita.estado==="Completada"?<Section title="Cobro"><Pressable style={s.charge} onPress={()=>router.push({pathname:"/cobrar-cita/[id]",params:{id:String(id)}})}><Text style={s.chargeText}>💰 Registrar cobro del servicio</Text></Pressable></Section>:null}\n   {cita.notas?<Section title="Notas"><Text style={s.notes}>{cita.notas}</Text></Section>:null}\n   <Section title="WhatsApp"><View style={s.actions}><Pressable style={s.whatsapp} onPress={()=>abrirWhatsApp("confirmacion")}><Text style={s.whatsappText}>💬 Enviar confirmación</Text></Pressable><Pressable style={s.whatsappOutline} onPress={()=>abrirWhatsApp("recordatorio")}><Text style={s.whatsappOutlineText}>🔔 Enviar recordatorio</Text></Pressable></View><Text style={s.whatsappHint}>Abre WhatsApp con el mensaje listo para revisar y enviar. No cambia el estado de la cita.</Text></Section>\n   <Section title="Cambiar estado"><View style={s.actions}><StatusButton text="Pendiente" disabled={actualizando||cita.estado==="Pendiente"} onPress={()=>confirmarCambio("Pendiente","Pendiente")}/><StatusButton text="Confirmar" disabled={actualizando||cita.estado==="Confirmada"} onPress={()=>confirmarCambio("Confirmada","Confirmada")}/><StatusButton text="En proceso" disabled={actualizando||cita.estado==="EnProceso"} onPress={()=>confirmarCambio("EnProceso","En proceso")}/><StatusButton text="Completada" disabled={actualizando||cita.estado==="Completada"} onPress={()=>confirmarCambio("Completada","Completada")}/><StatusButton text="No asistió" disabled={actualizando||cita.estado==="NoAsistio"} onPress={()=>confirmarCambio("NoAsistio","No asistió",true)}/><StatusButton text="Cancelar cita" danger disabled={actualizando||cita.estado==="Cancelada"} onPress={()=>confirmarCambio("Cancelada","Cancelada",true)}/></View>{actualizando?<View style={s.updating}><ActivityIndicator size="small"/><Text style={s.muted}>Actualizando...</Text></View>:null}</Section>
 </>}</ScrollView></SafeAreaView>;
}
function StatusButton({text,onPress,disabled,danger=false}:{text:string;onPress:()=>void;disabled:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.statusBtn,danger&&s.statusDanger,disabled&&s.statusDisabled]}><Text style={[s.statusText,danger&&s.statusDangerText]}>{text}</Text></Pressable>}\nfunction Section({title,children}:{title:string;children:any}){return <View style={s.card}><Text style={s.section}>{title}</Text>{children}</View>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
function nombre(p?:{nombre?:string;apellidos?:string}){return[p?.nombre,p?.apellidos].filter(Boolean).join(" ")}
function estado(v?:string){return v==="EnProceso"?"En proceso":v==="NoAsistio"?"No asistió":v??"Pendiente"}
function moneda(v?:number){return new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(v??0))}
function fechaHora(raw?:string){if(!raw)return"Fecha no disponible";const v=/Z$|[+-]\d{2}:\d{2}$/.test(raw)?raw:`${raw}Z`;return new Intl.DateTimeFormat("es-CR",{timeZone:"America/Costa_Rica",weekday:"long",day:"numeric",month:"long",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(v))}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},loading:{flex:1,alignItems:"center",justifyContent:"center",gap:10,backgroundColor:"#f4f6f8"},muted:{color:"#64748b"},top:{padding:20,paddingTop:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:"#2563eb",fontWeight:"700"},title:{fontSize:18,fontWeight:"900",color:"#111827"},content:{padding:20,paddingTop:4,paddingBottom:40},hero:{backgroundColor:"#111827",borderRadius:24,padding:22,marginBottom:14},heroTime:{color:"#cbd5e1",textTransform:"capitalize"},heroService:{color:"#fff",fontSize:26,fontWeight:"900",marginTop:8},heroStatus:{color:"#93c5fd",fontWeight:"800",marginTop:8},card:{backgroundColor:"#fff",borderRadius:20,padding:18,marginBottom:14},section:{fontSize:17,fontWeight:"900",color:"#111827",marginBottom:10},row:{flexDirection:"row",justifyContent:"space-between",gap:20,paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e2e8f0"},label:{color:"#64748b"},value:{color:"#111827",fontWeight:"700",textAlign:"right",flex:1},notes:{color:"#475569",lineHeight:21},actions:{gap:9},charge:{backgroundColor:"#2563eb",borderRadius:14,paddingVertical:15,paddingHorizontal:14,alignItems:"center"},chargeText:{color:"#fff",fontWeight:"900"},whatsapp:{backgroundColor:"#166534",borderRadius:14,paddingVertical:14,paddingHorizontal:14,alignItems:"center"},whatsappText:{color:"#fff",fontWeight:"900"},whatsappOutline:{borderWidth:1,borderColor:"#86efac",backgroundColor:"#f0fdf4",borderRadius:14,paddingVertical:14,paddingHorizontal:14,alignItems:"center"},whatsappOutlineText:{color:"#166534",fontWeight:"900"},whatsappHint:{color:"#64748b",fontSize:11,lineHeight:17,marginTop:10},statusBtn:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:14,paddingVertical:13,paddingHorizontal:14,alignItems:"center"},statusText:{fontWeight:"800",color:"#334155"},statusDanger:{borderColor:"#fecdd3",backgroundColor:"#fff1f2"},statusDangerText:{color:"#be123c"},statusDisabled:{opacity:.35},updating:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,marginTop:12},error:{color:"#9f1239"}});
