import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import api from "@/src/services/api";
type Venta={id:number;clienteId?:number|null;cliente?:string;total?:number;metodoPago?:string};
const FALLBACK=["Efectivo","SINPE Movil","Tarjeta","Transferencia"];
export default function CobrarVenta(){
 const{id}=useLocalSearchParams<{id:string}>();const[v,setV]=useState<Venta|null>(null),[metodos,setMetodos]=useState<string[]>(FALLBACK),[monto,setMonto]=useState(""),[metodo,setMetodo]=useState("Efectivo"),[notas,setNotas]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const[a,b]=await Promise.all([api.get(`/Ventas/${id}`),api.get("/Ventas/metodos-pago")]);setV(a.data);setMonto(String(Number(a.data?.total??0)));const ms=Array.isArray(b.data)&&b.data.length?b.data:FALLBACK;setMetodos(ms);setMetodo(a.data?.metodoPago||ms[0])}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible preparar el cobro.")}finally{setLoading(false)}})()},[id]);
 const total=Number(v?.total??0),pagado=Number(monto)||0,saldo=useMemo(()=>Math.max(0,total-pagado),[total,pagado]),tipo=pagado<=0?"Pendiente":pagado<total?"Pago parcial":"Pagado completo";
 const registrar=async()=>{if(!v)return;if(!Number.isFinite(Number(monto))||pagado<0)return setError("Ingresa un monto válido.");if(pagado>total)return setError("El monto pagado no puede superar el total.");if(pagado<total&&!v.clienteId)return setError("Para dejar un saldo pendiente, la venta debe tener un cliente.");try{setSaving(true);setError("");const r=await api.post("/CobrosVentas/registrar",{ventaId:v.id,montoPagado:pagado,metodoPago:pagado>0?metodo:null,notas:notas.trim()||null});const estado=r.data?.estado??"Registrado";Alert.alert("Cobro registrado",estado==="Pagada"?"La venta quedó pagada completa.":estado==="Parcial"?"El pago parcial fue registrado y el saldo quedó pendiente.":"La venta quedó pendiente de pago.",[{text:"Ver venta",onPress:()=>router.replace(`/venta/${v.id}`)}])}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible registrar el cobro.")}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/><Text>Cargando cobro...</Text></SafeAreaView>;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Volver</Text></Pressable><Text style={s.title}>Registrar cobro</Text><Text style={s.sub}>Venta #{v?.id} · {v?.cliente||"Sin cliente"}</Text>{error?<Text style={s.error}>{error}</Text>:null}
 <View style={s.hero}><Text style={s.heroLabel}>Total de la venta</Text><Text style={s.heroValue}>{money(total)}</Text></View>
 {!v?.clienteId?<Text style={s.info}>Esta venta no tiene cliente. Debe pagarse completa; los pagos parciales o pendientes requieren un cliente.</Text>:null}
 <Text style={s.label}>Opciones rápidas</Text><View style={s.actions}><Pressable onPress={()=>setMonto(String(total))} style={s.quick}><Text style={s.quickText}>✓ Pagado completo</Text></Pressable><Pressable disabled={!v?.clienteId} onPress={()=>setMonto("0")} style={[s.quick,!v?.clienteId&&s.disabled]}><Text style={s.quickText}>⏳ Dejar pendiente</Text></Pressable></View>
 <Text style={s.label}>Monto pagado ahora</Text><TextInput value={monto} onChangeText={setMonto} keyboardType="decimal-pad" style={s.input}/>
 <Text style={s.label}>Método de pago</Text><View style={s.chips}>{metodos.map(x=><Pressable disabled={pagado<=0} key={x} onPress={()=>setMetodo(x)} style={[s.chip,metodo===x&&pagado>0&&s.chipOn,pagado<=0&&s.disabled]}><Text style={[s.chipText,metodo===x&&pagado>0&&s.chipTextOn]}>{x}</Text></Pressable>)}</View>
 <View style={s.summary}><Row a="Pagado ahora" b={money(pagado)}/><Row a="Saldo pendiente" b={money(saldo)}/><Row a="Resultado" b={tipo}/></View>
 <Text style={s.label}>Notas</Text><TextInput value={notas} onChangeText={setNotas} multiline placeholder="Ej: saldo pendiente para el viernes..." style={[s.input,s.notes]}/>
 <Pressable disabled={saving} onPress={registrar} style={[s.pay,saving&&s.disabled]}><Text style={s.payText}>{saving?"Registrando...":"💳 Registrar cobro"}</Text></Pressable><Pressable disabled={saving} onPress={()=>router.replace(`/venta/${id}`)}><Text style={s.skip}>Cerrar sin registrar cobro</Text></Pressable>
 </ScrollView></SafeAreaView>
}
function Row({a,b}:{a:string;b:string}){return <View style={s.row}><Text style={s.summaryLabel}>{a}</Text><Text style={s.summaryValue}>{b}</Text></View>}const money=(v?:number)=>new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(v??0));
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:45},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},back:{color:"#2563eb",fontWeight:"800",marginTop:8},title:{fontSize:30,fontWeight:"900",color:"#111827",marginTop:20},sub:{color:"#64748b",marginTop:4},error:{backgroundColor:"#fff1f2",color:"#be123c",padding:12,borderRadius:12,marginTop:14},info:{backgroundColor:"#eff6ff",color:"#1e40af",padding:13,borderRadius:13,marginTop:14,lineHeight:19},hero:{backgroundColor:"#111827",borderRadius:22,padding:20,marginTop:18},heroLabel:{color:"#cbd5e1"},heroValue:{color:"#fff",fontSize:32,fontWeight:"900",marginTop:5},label:{fontWeight:"900",color:"#111827",marginTop:20,marginBottom:9},actions:{flexDirection:"row",gap:8},quick:{flex:1,backgroundColor:"#fff",borderRadius:14,padding:13,alignItems:"center",borderWidth:1,borderColor:"#e2e8f0"},quickText:{fontWeight:"800",color:"#334155",fontSize:12},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:14,paddingHorizontal:14,paddingVertical:12},notes:{minHeight:76,textAlignVertical:"top"},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e2e8f0",borderRadius:999,paddingHorizontal:12,paddingVertical:9},chipOn:{backgroundColor:"#111827",borderColor:"#111827"},chipText:{color:"#334155",fontWeight:"700",fontSize:12},chipTextOn:{color:"#fff"},summary:{backgroundColor:"#fff",borderRadius:18,padding:16,marginTop:18,gap:12},row:{flexDirection:"row",justifyContent:"space-between",gap:15},summaryLabel:{color:"#64748b"},summaryValue:{color:"#111827",fontWeight:"900"},pay:{backgroundColor:"#2563eb",borderRadius:16,padding:16,alignItems:"center",marginTop:20},payText:{color:"#fff",fontWeight:"900",fontSize:16},skip:{textAlign:"center",color:"#64748b",fontWeight:"700",padding:16},disabled:{opacity:.45}});
