import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import api from "@/src/services/api";import {telUrl,whatsappUrl} from "@/src/services/phone";import {dinero,fechaHora,obtenerRegional,REGIONAL_DEFAULT,Regional} from "@/src/services/regional";
type Cita={id:number;fechaInicio?:string;precio?:number;estado?:string;servicio?:{nombre?:string};profesional?:{nombre?:string;apellidos?:string};sucursal?:{nombre?:string}};
type Historial={cliente?:{id:number;nombre?:string;apellidos?:string;telefono?:string;email?:string;fechaNacimiento?:string;notas?:string;deuda?:number};resumen?:{totalCitas?:number;citasCompletadas?:number;canceladas?:number;noAsistio?:number;totalGastado?:number;deuda?:number};citas?:Cita[]};
export default function ClienteDetalle(){
 const {id}=useLocalSearchParams<{id:string}>();const[regional,setRegional]=useState<Regional>(REGIONAL_DEFAULT),[data,setData]=useState<Historial|null>(null),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState("");
 const cargar=useCallback(async(r=false)=>{r?setRefresh(true):setLoading(true);setError("");try{const x=await api.get(`/Clientes/${id}/historial`);setData(x.data??null)}catch(e:any){setError(e?.response?.data?.mensaje??"No fue posible cargar el historial del cliente.")}finally{setLoading(false);setRefresh(false)}},[id]);
 useEffect(()=>{obtenerRegional().then(setRegional);cargar()},[cargar]);if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/><Text style={s.muted}>Cargando cliente...</Text></SafeAreaView>;
 const cl=data?.cliente,r=data?.resumen,citas=data?.citas??[];const full=[cl?.nombre,cl?.apellidos].filter(Boolean).join(" ")||"Cliente";
 const whatsapp=()=>{const url=whatsappUrl(cl?.telefono);if(url)Linking.openURL(url)};
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>cargar(true)}/>}>
 <Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Clientes</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}
 {data?<><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>{(cl?.nombre?.[0]??"?").toUpperCase()}</Text></View><Text style={s.title}>{full}</Text><Pressable onPress={()=>router.push({pathname:"/editar-cliente/[id]",params:{id:String(id)}})}><Text style={s.edit}>Editar cliente</Text></Pressable><Text style={s.contact}>{cl?.telefono||"Sin teléfono"}{cl?.email?` · ${cl.email}`:""}</Text>
 <View style={s.actions}>{cl?.telefono?<Pressable style={s.whatsapp} onPress={whatsapp}><Text style={s.whatsappText}>💬 WhatsApp</Text></Pressable>:null}{cl?.telefono?<Pressable style={s.action} onPress={()=>{const url=telUrl(cl.telefono);if(url)Linking.openURL(url)}}><Text style={s.actionText}>📞 Llamar</Text></Pressable>:null}</View></View>
 <Text style={s.section}>Resumen</Text><View style={s.grid}><Metric label="Citas" value={r?.totalCitas??0}/><Metric label="Completadas" value={r?.citasCompletadas??0}/><Metric label="Canceladas" value={r?.canceladas??0}/><Metric label="No asistió" value={r?.noAsistio??0}/></View>
 <View style={s.money}><Text style={s.moneyLabel}>Total gastado</Text><Text style={s.moneyValue}>{dinero(r?.totalGastado,regional)}</Text><Text style={[s.moneyLabel,{marginTop:12}]}>Saldo pendiente</Text><Text style={[s.moneyValue,Number(r?.deuda)>0&&s.debt]}>{dinero(r?.deuda,regional)}</Text></View>
 {cl?.notas?<><Text style={s.section}>Notas</Text><View style={s.box}><Text style={s.notes}>{cl.notas}</Text></View></>:null}
 <Text style={s.section}>Historial de citas</Text><View style={s.box}>{citas.length?citas.map((x,i)=><Pressable key={x.id} onPress={()=>router.push(`/cita/${x.id}`)} style={[s.cita,i===citas.length-1&&s.last]}><View style={s.citaBody}><Text style={s.citaTitle}>{x.servicio?.nombre??"Servicio"}</Text><Text style={s.citaDetail}>{fechaHora(x.fechaInicio,regional,{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"})} · {[x.profesional?.nombre,x.profesional?.apellidos].filter(Boolean).join(" ")||"Profesional"}</Text><Text style={s.citaDetail}>{x.estado??"Pendiente"} · {dinero(x.precio,regional)}</Text></View><Text style={s.chevron}>›</Text></Pressable>):<Text style={s.empty}>Este cliente todavía no tiene citas.</Text>}</View></>:null}
 </ScrollView></SafeAreaView>
}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},content:{padding:20,paddingBottom:40},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},muted:{color:"#64748b"},back:{color:"#2563eb",fontWeight:"800",marginTop:8},error:{color:"#be123c",marginTop:14},profile:{backgroundColor:"#fff",borderRadius:22,padding:20,alignItems:"center",marginTop:20},avatar:{width:66,height:66,borderRadius:33,backgroundColor:"#e2e8f0",alignItems:"center",justifyContent:"center"},avatarText:{fontSize:25,fontWeight:"900",color:"#334155"},title:{fontSize:24,fontWeight:"900",color:"#111827",marginTop:12,textAlign:"center"},edit:{color:"#2563eb",fontWeight:"900",marginTop:8},contact:{color:"#64748b",marginTop:5,textAlign:"center"},actions:{flexDirection:"row",gap:10,marginTop:18},whatsapp:{backgroundColor:"#166534",borderRadius:13,paddingHorizontal:16,paddingVertical:11},whatsappText:{color:"#fff",fontWeight:"900"},action:{backgroundColor:"#f1f5f9",borderRadius:13,paddingHorizontal:16,paddingVertical:11},actionText:{color:"#334155",fontWeight:"900"},section:{fontSize:18,fontWeight:"900",color:"#111827",marginTop:24,marginBottom:11},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},metric:{width:"47%",flexGrow:1,backgroundColor:"#fff",borderRadius:16,padding:15},metricValue:{fontSize:24,fontWeight:"900",color:"#111827"},metricLabel:{color:"#64748b",fontSize:12,marginTop:3},money:{backgroundColor:"#111827",borderRadius:18,padding:18,marginTop:12},moneyLabel:{color:"#94a3b8",fontSize:12},moneyValue:{color:"#fff",fontSize:22,fontWeight:"900",marginTop:3},debt:{color:"#fda4af"},box:{backgroundColor:"#fff",borderRadius:18,paddingHorizontal:16},notes:{color:"#334155",lineHeight:20,paddingVertical:15},cita:{flexDirection:"row",alignItems:"center",paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#e5e7eb"},last:{borderBottomWidth:0},citaBody:{flex:1},citaTitle:{fontWeight:"900",color:"#111827"},citaDetail:{color:"#64748b",fontSize:12,marginTop:3},chevron:{fontSize:28,color:"#94a3b8",marginLeft:8},empty:{paddingVertical:25,textAlign:"center",color:"#64748b"}});
